const {describe,it}=require('node:test'); const assert=require('node:assert/strict'); const fs=require('fs'); const path=require('path'); const ROOT=path.join(__dirname,'..');
describe('Stage 4 contracts',()=>{
 it('has two config markets with zones/status/currency',()=>{const {MARKETS}=require('../config/marketplace'); assert.ok(MARKETS.length>=2); for(const m of MARKETS) assert.ok(m.id&&m.zones.length&&m.defaultCurrency&&['draft','soft_launch','live','paused'].includes(m.status));});
 it('payment port is provider based and demo-capable',()=>{const src=fs.readFileSync(path.join(ROOT,'services/paymentPort.js'),'utf8'); assert.match(src,/Demo|demo/); assert.match(src,/Paystack|paystack/); assert.match(src,/initiateDeposit/); assert.match(src,/verify/);});
 it('merchant API has JWT, idempotency and business constraints',()=>{const src=fs.readFileSync(path.join(ROOT,'routes/merchant.routes.js'),'utf8'); assert.match(src,/verifyToken/); assert.match(src,/Idempotency-Key/); assert.match(src,/channel:\s*'business'/); assert.match(src,/reference/);});
 it('generic market and deposit routes exist',()=>{const app=fs.readFileSync(path.join(ROOT,'app.js'),'utf8'); assert.match(app,/\/api\/markets/); assert.match(app,/\/api\/merchant/); const wallet=fs.readFileSync(path.join(ROOT,'routes/wallet.routes.js'),'utf8'); assert.match(wallet,/deposit\/intent/); assert.match(wallet,/deposit\/verify/);});
 it('reliability honors MIN_SAMPLE_JOBS',()=>{const src=fs.readFileSync(path.join(ROOT,'services/zoneScoreboard.js'),'utf8'); assert.match(src,/MIN_SAMPLE_JOBS/); assert.match(src,/Insufficient data/); assert.match(fs.readFileSync(path.join(ROOT,'routes/market.routes.js'),'utf8'),/reliability/); assert.match(fs.readFileSync(path.join(ROOT,'client/src/pages/ClientDashboard.jsx'),'utf8'),/\/api\/markets/);});
 it('money engine remains present and routes do not introduce wallet mutation for merchant flow',()=>{const money=fs.readFileSync(path.join(ROOT,'services/errandMoney.js'),'utf8'); assert.match(money,/releaseHold/); assert.match(money,/refundHold/); const merchant=fs.readFileSync(path.join(ROOT,'routes/merchant.routes.js'),'utf8'); assert.doesNotMatch(merchant,/UPDATE wallets SET/);});
});
