module.exports = Object.freeze({
  ESCROW_RELEASE_HOURS: 24,
  DISPUTE_WINDOW_HOURS: 24,
  JOB_EXPIRE_HOURS: 48,
  DEFAULT_DURATION_MINUTES: 90,
  SUPPLY_GATE_RUNNERS: 15,
  MIN_SAMPLE_JOBS: 10,
  ZONE_HEALTH: Object.freeze({
    median_accept_minutes_early: 20,
    median_accept_minutes_strong: 12,
    accept_rate_early: 0.70,
    accept_rate_strong: 0.85,
    completion_rate_early: 0.85,
    completion_rate_strong: 0.92,
    dispute_rate_early_max: 0.05,
    dispute_rate_strong_max: 0.02,
  }),
  PRIMARY_MARKET: Object.freeze({
    id: process.env.PRIMARY_MARKET_ID || 'ng-lagos',
    country: process.env.PRIMARY_MARKET_COUNTRY || 'Nigeria',
    country_iso2: process.env.PRIMARY_MARKET_COUNTRY_ISO2 || 'NG',
    city: process.env.PRIMARY_MARKET_CITY || 'Lagos',
    defaultCurrency: process.env.PRIMARY_MARKET_CURRENCY || 'NGN',
    zones: Object.freeze((process.env.PRIMARY_MARKET_ZONES || 'Central,North').split(',').map((z) => z.trim()).filter(Boolean)),
    status: process.env.PRIMARY_MARKET_STATUS || 'live',
    display_name: process.env.PRIMARY_MARKET_DISPLAY_NAME || process.env.PRIMARY_MARKET_CITY || 'Lagos',
    require_verified_runners: process.env.PRIMARY_MARKET_REQUIRE_VERIFIED_RUNNERS !== 'false',
    insurance_mode: process.env.PRIMARY_MARKET_INSURANCE_MODE || 'off', verification_mode: process.env.PRIMARY_MARKET_VERIFICATION_MODE || 'manual',
    supply_gate: 15,
    support_email: process.env.SUPPORT_EMAIL || '',
  }),
  MARKETS: Object.freeze([
    Object.freeze({ id: process.env.PRIMARY_MARKET_ID || 'ng-lagos', name: 'Lagos', city: process.env.PRIMARY_MARKET_CITY || 'Lagos', country_iso2: process.env.PRIMARY_MARKET_COUNTRY_ISO2 || 'NG', defaultCurrency: process.env.PRIMARY_MARKET_CURRENCY || 'NGN', zones: Object.freeze((process.env.PRIMARY_MARKET_ZONES || 'Central,North').split(',').map((z) => z.trim()).filter(Boolean)), status: process.env.PRIMARY_MARKET_STATUS || 'live', display_name: process.env.PRIMARY_MARKET_DISPLAY_NAME || process.env.PRIMARY_MARKET_CITY || 'Lagos', require_verified_runners: process.env.PRIMARY_MARKET_REQUIRE_VERIFIED_RUNNERS !== 'false', insurance_mode: process.env.PRIMARY_MARKET_INSURANCE_MODE || 'off', verification_mode: process.env.PRIMARY_MARKET_VERIFICATION_MODE || 'manual', supply_gate: 15, support_email: process.env.SUPPORT_EMAIL || '' }),
    Object.freeze({ id: 'ng-ibadan', name: 'Ibadan', city: 'Ibadan', country_iso2: 'NG', defaultCurrency: 'NGN', zones: Object.freeze(['Central','North']), status: 'draft', display_name: 'Ibadan', require_verified_runners: false, insurance_mode: 'off', verification_mode: 'off', supply_gate: 15, support_email: process.env.SUPPORT_EMAIL || '' }),
  ]),
  MIN_SAMPLE_JOBS: 10,
  MAX_ACTIVE_LAUNCH_ZONES: 5,
  EXPAND_AFTER_HEALTHY_WEEKS: 4,
  WEBHOOK_MAX_RETRIES: 3,
  WEBHOOK_MAX_PER_USER: 5,
  WEBHOOK_RETRY_BACKOFF_SECONDS: [5, 30, 120],
  MAX_HOLD_AGE_HOURS: 72,
});
